### ISSUE TITLE
Labels on 2d studies don't 100% work

### ISSUE THREAD

**Issue by Thaddeus-Maximus** [RoseGPE/RoseLapWeb#6]
![image](https://user-images.githubusercontent.com/11543788/42569042-43473a1c-84dd-11e8-9491-cd385ff4f989.png)

The label (A) should completely ovverride the labels on this axis

**Comment by em4573** [comment]
I'm not sure how to implement that on the study definition side. If you have a bright idea let me know

**Comment by Thaddeus-Maximus** [comment]
It's fully supported after all
