### ISSUE TITLE
Study plots don't take up proper space

### ISSUE THREAD

**Issue by Thaddeus-Maximus** [RoseGPE/RoseLapWeb#8]
Plots don't take up the full screen width, and they also are too tall.

![image](https://user-images.githubusercontent.com/11543788/42569149-8f8f518e-84dd-11e8-8b5a-9ccde729bbe8.png)

**Comment by Thaddeus-Maximus** [comment]
The width for 1-D is partly because there's a secondary plot on the 1-d studies that isn't needed, so delet that

**Comment by em4573** [comment]
Do you not want a plot with all of the times/points? Line charts are not particularly large so having both plots takes better advantage of screen real estate.
